INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

INSERT INTO BOARD
VALUE(PNO, TITLE, EDITOR, P_PWD, CONTENTS, VIEW_COUNT, CRE_DATE)
VALUES(BOARD_PNO_SEQ.NEXTVAL, '글 테스트', 'tester', 'test123', '글 내용 테스트', 0, SYSDATE);

COMMIT;