--회원 테이블 생성
CREATE TABLE MEMBERS(
    MNO NUMBER NOT NULL,
    MNAME VARCHAR2(60) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    GENDER VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    RECOVERY_EMAIL VARCHAR2(30),
    PHONE_NO NUMBER,
    PWD VARCHAR2(20) NOT NULL
);

--회원 정보 테이블의 논리명 지정
COMMENT ON TABLE MEMBERS IS '회원 정보';

COMMENT ON COLUMN MEMBERS.MNO IS '회원 번호';
COMMENT ON COLUMN MEMBERS.MNAME IS '회원 이름';
COMMENT ON COLUMN MEMBERS.BIRTH_DATE IS '회원 생년월일';
COMMENT ON COLUMN MEMBERS.GENDER IS '회원 성별';
COMMENT ON COLUMN MEMBERS.EMAIL IS '회원 이메일';
COMMENT ON COLUMN MEMBERS.RECOVERY_EMAIL IS '복구 이메일';
COMMENT ON COLUMN MEMBERS.PHONE_NO IS '전화번호';
COMMENT ON COLUMN MEMBERS.PWD IS '회원 비밀번호';

--MNO 컬럼을 MEMBERS 테이블의 PRIMARY 키 지정
ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_MNO_PK PRIMARY KEY(MNO);

--EMAIL 컬럼을 유니크 키로 지정
ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_EMAIL_UK UNIQUE(EMAIL);

--MNO 컬럼에 사용할 SEQUENCE 생성
CREATE SEQUENCE MEMBERS_MNO_SEQ
INCREMENT BY 1
START WITH 1;

--게시판 테이블 생성
CREATE TABLE BOARD(
    PNO NUMBER NOT NULL,
    TITLE VARCHAR2(60) NOT NULL,
    EDITOR VARCHAR2(60) NOT NULL,
    P_PWD VARCHAR2(20) NOT NULL,
    CONTENTS VARCHAR2(3000) NOT NULL,
    VIEW_COUNT NUMBER NOT NULL,
    CRE_DATE DATE NOT NULL,
    MNO CONSTRAINT BOARD_MEMBERS_FK REFERENCES MEMBERS(MNO)
);

drop table board;

--게시판 테이블의 논리명 지정
COMMENT ON TABLE BOARD IS '게시판';

COMMENT ON COLUMN BOARD.PNO IS '게시글 번호';
COMMENT ON COLUMN BOARD.TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.EDITOR IS '작성자';
COMMENT ON COLUMN BOARD.P_PWD IS '게시글 비밀번호';
COMMENT ON COLUMN BOARD.CONTENTS IS '게시글 내용';
COMMENT ON COLUMN BOARD.VIEW_COUNT IS '조회수';
COMMENT ON COLUMN BOARD.CRE_DATE IS '작성일';
COMMENT ON COLUMN BOARD.MNO IS '회원 번호';

--PNO 컬럼을 BOARD 테이블의 PRIMARY키 생성
ALTER TABLE BOARD
ADD CONSTRAINT BOARD_PNO_PK PRIMARY KEY(PNO);

--PNO 컬럼에 사용할 SEQUENCE 생성
CREATE SEQUENCE BOARD_PNO_SEQ
INCREMENT BY 1
START WITH 1;

drop SEQUENCE BOARD_PNO_SEQ;
